### PR TITLE
feat: update readme

### PR DESCRIPTION
**Pull request by Codykilpatrick**
Updated the readme to boiler-plate the development section

### CODE REVIEW

**Review by mjlueder — APPROVED** [review]
Also beautiful!

**Comment by mjlueder** [comment]
@Codykilpatrick does it alert you to there being conflicts here?

**Comment by WarmSkin** [comment]
Nice!

**Review by WarmSkin — APPROVED** [review]
Nice!

**Review by robfrid06 — APPROVED** [review]
I felt left out, so I'm giving my input.

**Pull request merged**
